// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package signaref

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BusinessDetails struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LicenceType          string   `protobuf:"bytes,2,opt,name=licenceType,proto3" json:"licenceType,omitempty"`
	LicenceCode          string   `protobuf:"bytes,3,opt,name=licenceCode,proto3" json:"licenceCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessDetails) Reset()         { *m = BusinessDetails{} }
func (m *BusinessDetails) String() string { return proto.CompactTextString(m) }
func (*BusinessDetails) ProtoMessage()    {}
func (*BusinessDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *BusinessDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessDetails.Unmarshal(m, b)
}
func (m *BusinessDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessDetails.Marshal(b, m, deterministic)
}
func (m *BusinessDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessDetails.Merge(m, src)
}
func (m *BusinessDetails) XXX_Size() int {
	return xxx_messageInfo_BusinessDetails.Size(m)
}
func (m *BusinessDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessDetails.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessDetails proto.InternalMessageInfo

func (m *BusinessDetails) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *BusinessDetails) GetLicenceType() string {
	if m != nil {
		return m.LicenceType
	}
	return ""
}

func (m *BusinessDetails) GetLicenceCode() string {
	if m != nil {
		return m.LicenceCode
	}
	return ""
}

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ContactNo            string   `protobuf:"bytes,3,opt,name=contactNo,proto3" json:"contactNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Person) GetContactNo() string {
	if m != nil {
		return m.ContactNo
	}
	return ""
}

type Location struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Latitude             string   `protobuf:"bytes,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            string   `protobuf:"bytes,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Location) GetLatitude() string {
	if m != nil {
		return m.Latitude
	}
	return ""
}

func (m *Location) GetLongitude() string {
	if m != nil {
		return m.Longitude
	}
	return ""
}

type Address struct {
	Line1                string   `protobuf:"bytes,1,opt,name=line1,proto3" json:"line1,omitempty"`
	Line2                string   `protobuf:"bytes,2,opt,name=line2,proto3" json:"line2,omitempty"`
	Line3                string   `protobuf:"bytes,3,opt,name=line3,proto3" json:"line3,omitempty"`
	Street               string   `protobuf:"bytes,4,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	Country              string   `protobuf:"bytes,7,opt,name=country,proto3" json:"country,omitempty"`
	Postalcode           string   `protobuf:"bytes,8,opt,name=postalcode,proto3" json:"postalcode,omitempty"`
	Pobox                string   `protobuf:"bytes,9,opt,name=pobox,proto3" json:"pobox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{3}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetLine1() string {
	if m != nil {
		return m.Line1
	}
	return ""
}

func (m *Address) GetLine2() string {
	if m != nil {
		return m.Line2
	}
	return ""
}

func (m *Address) GetLine3() string {
	if m != nil {
		return m.Line3
	}
	return ""
}

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Address) GetPostalcode() string {
	if m != nil {
		return m.Postalcode
	}
	return ""
}

func (m *Address) GetPobox() string {
	if m != nil {
		return m.Pobox
	}
	return ""
}

type GeneralResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralResponse) Reset()         { *m = GeneralResponse{} }
func (m *GeneralResponse) String() string { return proto.CompactTextString(m) }
func (*GeneralResponse) ProtoMessage()    {}
func (*GeneralResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{4}
}

func (m *GeneralResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralResponse.Unmarshal(m, b)
}
func (m *GeneralResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralResponse.Marshal(b, m, deterministic)
}
func (m *GeneralResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralResponse.Merge(m, src)
}
func (m *GeneralResponse) XXX_Size() int {
	return xxx_messageInfo_GeneralResponse.Size(m)
}
func (m *GeneralResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralResponse proto.InternalMessageInfo

func (m *GeneralResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GeneralResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GeneralResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*BusinessDetails)(nil), "signaref.BusinessDetails")
	proto.RegisterType((*Person)(nil), "signaref.Person")
	proto.RegisterType((*Location)(nil), "signaref.Location")
	proto.RegisterType((*Address)(nil), "signaref.Address")
	proto.RegisterType((*GeneralResponse)(nil), "signaref.GeneralResponse")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x6a, 0xe3, 0x30,
	0x10, 0xc6, 0xc9, 0x6e, 0xe2, 0x38, 0xda, 0x85, 0x80, 0x58, 0x16, 0xb1, 0x2c, 0x25, 0xf8, 0xd4,
	0x53, 0xa1, 0xcd, 0x13, 0xf4, 0x0f, 0xf4, 0x52, 0x4a, 0x08, 0x2d, 0xf4, 0xaa, 0xc8, 0xd3, 0x20,
	0x90, 0x35, 0x46, 0x9a, 0x40, 0xf3, 0xb0, 0x7d, 0x97, 0x32, 0x92, 0xe5, 0xa6, 0xf4, 0xa6, 0xdf,
	0x37, 0xf2, 0x4f, 0x9f, 0x65, 0x8b, 0xdf, 0x06, 0xbb, 0x0e, 0xfd, 0x45, 0x1f, 0x90, 0x50, 0xd6,
	0xd1, 0xee, 0xbd, 0x0e, 0xf0, 0xda, 0x58, 0xb1, 0xbc, 0x39, 0x44, 0xeb, 0x21, 0xc6, 0x3b, 0x20,
	0x6d, 0x5d, 0x94, 0x52, 0x4c, 0xe9, 0xd8, 0x83, 0x9a, 0xac, 0x26, 0xe7, 0x8b, 0x6d, 0x5a, 0xcb,
	0x95, 0xf8, 0xe5, 0xac, 0x01, 0x6f, 0xe0, 0x89, 0x47, 0x3f, 0xd2, 0xe8, 0x34, 0x3a, 0xd9, 0x71,
	0x8b, 0x2d, 0xa8, 0x9f, 0x5f, 0x76, 0x70, 0xd4, 0x6c, 0x44, 0xb5, 0x81, 0x10, 0xd1, 0xf3, 0x09,
	0x5e, 0x77, 0xe3, 0x09, 0xbc, 0x96, 0x7f, 0xc4, 0x0c, 0x3a, 0x6d, 0xdd, 0xe0, 0xce, 0x20, 0xff,
	0x8b, 0x85, 0x41, 0x4f, 0xda, 0xd0, 0x23, 0x0e, 0xce, 0xcf, 0xa0, 0x79, 0x11, 0xf5, 0x03, 0x1a,
	0x4d, 0x36, 0x3b, 0xbf, 0xb5, 0xfe, 0x27, 0x6a, 0xa7, 0xc9, 0xd2, 0xa1, 0x2d, 0x95, 0x47, 0x66,
	0xb3, 0x43, 0xbf, 0xcf, 0xc3, 0xc1, 0x3c, 0x06, 0xcd, 0xfb, 0x44, 0xcc, 0xaf, 0xdb, 0x36, 0x40,
	0x8c, 0xdc, 0xcc, 0x59, 0x0f, 0x97, 0x83, 0x3a, 0x43, 0x49, 0xaf, 0x4a, 0xdf, 0x04, 0x25, 0x5d,
	0x0f, 0xc6, 0x0c, 0xf2, 0xaf, 0xa8, 0x22, 0x05, 0x00, 0x52, 0xd3, 0x14, 0x0f, 0xc4, 0x9d, 0x8d,
	0xa5, 0xa3, 0x9a, 0xe5, 0xce, 0xbc, 0x66, 0x43, 0x24, 0x4d, 0xa0, 0xaa, 0x6c, 0x48, 0x20, 0x95,
	0x98, 0x1b, 0x3c, 0x78, 0x0a, 0x47, 0x35, 0x4f, 0x79, 0x41, 0x79, 0x26, 0x44, 0x8f, 0x91, 0xb4,
	0x33, 0x7c, 0xed, 0x75, 0x1a, 0x9e, 0x24, 0xec, 0xeb, 0x71, 0x87, 0x6f, 0x6a, 0x91, 0x7d, 0x09,
	0x9a, 0x67, 0xb1, 0xbc, 0x07, 0x0f, 0x41, 0xbb, 0x2d, 0xc4, 0x1e, 0x7d, 0x84, 0x54, 0x86, 0x15,
	0xfc, 0x96, 0xb3, 0xed, 0xb4, 0x3c, 0x0c, 0x21, 0x60, 0x18, 0x3f, 0x0a, 0x03, 0x97, 0xe9, 0x20,
	0x46, 0xbd, 0x2f, 0x17, 0x57, 0x70, 0x57, 0xa5, 0xdf, 0x6b, 0xfd, 0x11, 0x00, 0x00, 0xff, 0xff,
	0xa9, 0x19, 0xb5, 0xcd, 0x6e, 0x02, 0x00, 0x00,
}
