// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vendor.proto

package signaref

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VendorDetails struct {
	Code                 int32                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId               string               `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	Website              string               `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	ContactPerson        *Person              `protobuf:"bytes,5,opt,name=contactPerson,proto3" json:"contactPerson,omitempty"`
	BusinessDetails      *BusinessDetails     `protobuf:"bytes,6,opt,name=businessDetails,proto3" json:"businessDetails,omitempty"`
	Location             *Location            `protobuf:"bytes,7,opt,name=location,proto3" json:"location,omitempty"`
	Address              *Address             `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Status               string               `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,10,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VendorDetails) Reset()         { *m = VendorDetails{} }
func (m *VendorDetails) String() string { return proto.CompactTextString(m) }
func (*VendorDetails) ProtoMessage()    {}
func (*VendorDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_f466d14b0fac1564, []int{0}
}

func (m *VendorDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VendorDetails.Unmarshal(m, b)
}
func (m *VendorDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VendorDetails.Marshal(b, m, deterministic)
}
func (m *VendorDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VendorDetails.Merge(m, src)
}
func (m *VendorDetails) XXX_Size() int {
	return xxx_messageInfo_VendorDetails.Size(m)
}
func (m *VendorDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_VendorDetails.DiscardUnknown(m)
}

var xxx_messageInfo_VendorDetails proto.InternalMessageInfo

func (m *VendorDetails) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VendorDetails) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VendorDetails) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *VendorDetails) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *VendorDetails) GetContactPerson() *Person {
	if m != nil {
		return m.ContactPerson
	}
	return nil
}

func (m *VendorDetails) GetBusinessDetails() *BusinessDetails {
	if m != nil {
		return m.BusinessDetails
	}
	return nil
}

func (m *VendorDetails) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *VendorDetails) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *VendorDetails) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VendorDetails) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

func init() {
	proto.RegisterType((*VendorDetails)(nil), "signaref.VendorDetails")
}

func init() { proto.RegisterFile("vendor.proto", fileDescriptor_f466d14b0fac1564) }

var fileDescriptor_f466d14b0fac1564 = []byte{
	// 416 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xc7, 0x95, 0x7e, 0x64, 0xb7, 0xee, 0x96, 0x52, 0x83, 0xc0, 0x44, 0x08, 0x56, 0x39, 0xad,
	0x8a, 0x94, 0x88, 0x22, 0x71, 0xa8, 0xc4, 0x81, 0x0f, 0x81, 0x90, 0x38, 0x20, 0x0b, 0xb8, 0x22,
	0x27, 0x9e, 0x8d, 0x2c, 0x39, 0x76, 0xe4, 0x71, 0xca, 0x9d, 0x57, 0xe0, 0xc6, 0x6b, 0xf5, 0x15,
	0x78, 0x10, 0xb4, 0x76, 0x42, 0x1a, 0x8e, 0xbd, 0x79, 0x66, 0x7e, 0x7f, 0x8f, 0x3d, 0xff, 0x21,
	0xab, 0x2b, 0x30, 0xd2, 0xba, 0xa2, 0x73, 0xd6, 0x5b, 0xba, 0x44, 0xd5, 0x18, 0xe1, 0x60, 0x9b,
	0x3d, 0x6d, 0xac, 0x6d, 0x34, 0x94, 0x21, 0x5f, 0xf5, 0xdb, 0xd2, 0xab, 0x16, 0xd0, 0x8b, 0xb6,
	0x8b, 0x68, 0xf6, 0x78, 0x00, 0x44, 0xa7, 0x4a, 0x61, 0x8c, 0xf5, 0xc2, 0x2b, 0x6b, 0x70, 0xa8,
	0xae, 0x6a, 0xdb, 0xb6, 0xd6, 0xc4, 0x28, 0xff, 0xbd, 0x4f, 0x4e, 0xbe, 0x85, 0x3e, 0xef, 0xc0,
	0x0b, 0xa5, 0x91, 0x52, 0x72, 0x50, 0x5b, 0x09, 0x2c, 0x59, 0x27, 0x9b, 0x43, 0x1e, 0xce, 0xbb,
	0x9c, 0x11, 0x2d, 0xb0, 0xbd, 0x75, 0xb2, 0x39, 0xe2, 0xe1, 0x4c, 0x1f, 0x90, 0xb4, 0x47, 0x70,
	0x1f, 0x25, 0xdb, 0x0f, 0xd9, 0x21, 0xa2, 0x8c, 0x2c, 0x7e, 0x40, 0x85, 0xca, 0x03, 0x3b, 0x08,
	0x85, 0x31, 0xa4, 0x2f, 0xc9, 0x49, 0x6d, 0x8d, 0x17, 0xb5, 0xff, 0x0c, 0x0e, 0xad, 0x61, 0x87,
	0xeb, 0x64, 0x73, 0x7c, 0x71, 0xb7, 0x18, 0xbf, 0x56, 0xc4, 0x3c, 0x9f, 0x63, 0xf4, 0x2d, 0x39,
	0xad, 0x7a, 0x54, 0x06, 0x10, 0x87, 0x47, 0xb2, 0x34, 0x28, 0x1f, 0x4d, 0xca, 0x37, 0x73, 0x80,
	0xff, 0xaf, 0xa0, 0x05, 0x59, 0x6a, 0x5b, 0x87, 0x49, 0xb0, 0x45, 0x50, 0xd3, 0x49, 0xfd, 0x69,
	0xa8, 0xf0, 0x7f, 0x0c, 0x7d, 0x46, 0x16, 0x42, 0x4a, 0x07, 0x88, 0x6c, 0x19, 0xf0, 0xb3, 0x09,
	0x7f, 0x1d, 0x0b, 0x7c, 0x24, 0x76, 0xb3, 0x40, 0x2f, 0x7c, 0x8f, 0xec, 0x28, 0xce, 0x22, 0x46,
	0xf4, 0x15, 0x59, 0x69, 0x81, 0xfe, 0x7b, 0xdf, 0x49, 0xe1, 0x41, 0x32, 0x12, 0x6e, 0xca, 0x8a,
	0x68, 0x50, 0x31, 0x3a, 0x58, 0x7c, 0x19, 0x1d, 0xe4, 0xc7, 0x3b, 0xfe, 0x6b, 0xc4, 0x2f, 0xae,
	0x13, 0x92, 0x46, 0x73, 0xa8, 0x24, 0x77, 0x38, 0x34, 0x0a, 0x3d, 0xb8, 0x21, 0xf3, 0x70, 0x7a,
	0xcf, 0xcc, 0xc0, 0xec, 0xc6, 0x54, 0x3e, 0x80, 0x01, 0x27, 0x34, 0x07, 0xec, 0xac, 0x41, 0xc8,
	0x9f, 0xfc, 0xbc, 0xfe, 0xf3, 0x6b, 0x8f, 0xe5, 0xf7, 0xca, 0xab, 0xe7, 0x65, 0x5c, 0xaf, 0xd2,
	0x0d, 0xd7, 0x5e, 0x26, 0xe7, 0xb4, 0x26, 0x67, 0xef, 0x95, 0xd6, 0xf3, 0x85, 0xb8, 0x4d, 0xa3,
	0x2c, 0x34, 0xba, 0x9f, 0x9f, 0xde, 0x68, 0xb4, 0x55, 0x5a, 0x5f, 0x26, 0xe7, 0x55, 0x1a, 0xbe,
	0xfd, 0xe2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xff, 0xfe, 0x1f, 0xe0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VendorClient is the client API for Vendor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VendorClient interface {
	RegisterVendor(ctx context.Context, in *VendorDetails, opts ...grpc.CallOption) (*GeneralResponse, error)
	FillVendorDetails(ctx context.Context, in *VendorDetails, opts ...grpc.CallOption) (*GeneralResponse, error)
}

type vendorClient struct {
	cc *grpc.ClientConn
}

func NewVendorClient(cc *grpc.ClientConn) VendorClient {
	return &vendorClient{cc}
}

func (c *vendorClient) RegisterVendor(ctx context.Context, in *VendorDetails, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/signaref.Vendor/RegisterVendor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vendorClient) FillVendorDetails(ctx context.Context, in *VendorDetails, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/signaref.Vendor/FillVendorDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VendorServer is the server API for Vendor service.
type VendorServer interface {
	RegisterVendor(context.Context, *VendorDetails) (*GeneralResponse, error)
	FillVendorDetails(context.Context, *VendorDetails) (*GeneralResponse, error)
}

func RegisterVendorServer(s *grpc.Server, srv VendorServer) {
	s.RegisterService(&_Vendor_serviceDesc, srv)
}

func _Vendor_RegisterVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendorDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServer).RegisterVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signaref.Vendor/RegisterVendor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServer).RegisterVendor(ctx, req.(*VendorDetails))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vendor_FillVendorDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VendorDetails)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VendorServer).FillVendorDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/signaref.Vendor/FillVendorDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VendorServer).FillVendorDetails(ctx, req.(*VendorDetails))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vendor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "signaref.Vendor",
	HandlerType: (*VendorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterVendor",
			Handler:    _Vendor_RegisterVendor_Handler,
		},
		{
			MethodName: "FillVendorDetails",
			Handler:    _Vendor_FillVendorDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vendor.proto",
}
